D={
"exi070":("Finalização após combinação entre dois jogadores, com guarda-redes.",
 "Dois grupos de cada lado, à entrada da área. O primeiro jogador passa em diagonal para o colega, que devolve em apoio ou cruza para a zona de finalização.\nO jogador que iniciou ataca o espaço e finaliza à baliza.\nAlternar os lados e o pé de finalização.",
 "Timing da desmarcação\nPasse para o espaço à frente do colega"),
"exi075":("Jogo por setores com balizas, trabalhando a saída e a ligação entre linhas.",
 "Espaço dividido em setores com a defesa de uma equipa e o ataque da outra em cada zona, e mini-balizas em ambos os lados.\nA equipa em posse tem de passar a bola de setor em setor até conseguir finalizar numa das balizas.\nOs jogadores não saem do seu setor.",
 "Apoio frontal para ligar setores\nDefesa compacta dentro do setor"),
"exi079":("Pressão em inferioridade e reação à perda (cão de caça).",
 "Dentro de um quadrado, uma equipa mantém a posse enquanto um grupo de caçadores tenta recuperar a bola.\nQuando recuperam, os caçadores ligam com os colegas fora do quadrado; os restantes esperam na área e entram em vaga para substituir.\nAlternar funções a cada série.",
 "Pressionar em grupo, fechando linhas\nNão perseguir a bola sozinho"),
"exi081":("Jogo lúdico de velocidade e precisão com três estações.",
 "Três estações, cada uma com arcos no chão, estacas em slalom e uma mini-baliza no fundo.\nCada equipa em fila faz o percurso em condução e termina com remate à mini-baliza.\nEstafeta entre equipas; vence quem tiver mais golos no menor tempo.",
 "Condução próxima nas estacas\nRemate controlado"),
"exi082":("Jogo competitivo com ataque à profundidade (bola na rotura).",
 "Jogo entre duas equipas num espaço amplo com jokers, que jogam com a equipa em posse.\nPonto quando a equipa consegue meter a bola nas costas da defesa adversária, para um colega que ataca a profundidade.\nGolo na baliza grande depois de uma rotura vale a dobrar.",
 "Momento da desmarcação de rutura\nPasse para o espaço, à frente do colega"),
"exi085":("Situações de 3x2 no corredor lateral com ataque à área.",
 "Espaço dividido por linhas que criam dois corredores laterais. Em cada corredor, 3 atacantes contra 2 defensores.\nOs atacantes procuram o cruzamento ou a entrada na área; os defensores tentam recuperar e sair em passe.\nAlternar os corredores a cada série.",
 "Sobreposição e combinação no corredor\nAtacar a área em timings diferentes"),
"exi086":("Remate de meia distância e reação defensiva imediata.",
 "Dois grupos junto a duas balizas em lados opostos. O jogador conduz, remata à baliza da frente e logo depois passa a defender o adversário que sai do outro lado.\nFluxo contínuo, com guarda-redes nas duas balizas.",
 "Remate cedo, sem esperar\nTransição rápida para defender"),
"exi087":("Criação ofensiva em 2x2 com dois jokers.",
 "Retângulo com 2x2 no interior e um joker em cada linha de fundo, que se desloca ao longo da linha.\nA equipa em posse tem de ligar de um joker ao outro para marcar ponto.\nOs jokers jogam a 1 ou 2 toques.",
 "Criar linha de passe com o corpo aberto\nTerceiro homem com o joker"),
"exi091":("Jogo lúdico de posse (pataleca) em roda.",
 "Dois grupos em roda, com um ou dois jogadores no meio de cada roda.\nA bola circula com toques rápidos; quem está no meio tenta intercetar.\nQuem errar o passe entra para o meio.",
 "Primeiro toque orientado\nComunicação na roda"),
"exi092":("Técnica de toque e controlo de bola em torneio de tekball.",
 "Mesas ou bancos no meio de cada campo, com duplas de cada lado.\nA bola é jogada por cima da mesa como no ténis, com as regras do tekball: sem tocar na mesa com o corpo e com um número limitado de toques.\nTorneio com rotação: quem ganha sobe de mesa.",
 "Controlo de bola com várias superfícies\nConcentração e precisão"),
"exi094":("Manutenção da posse com jokers e ataque à profundidade.",
 "Espaço dividido em duas zonas, com jokers nas linhas exteriores e na zona central.\nA equipa em posse faz um número de passes com a ajuda dos jokers e procura depois meter a bola nas costas para um colega que ataca o espaço.\nPontos para sequências de passes e para roturas bem conseguidas.",
 "Posse com o objetivo de progredir\nDesmarcação de rutura no momento do passe"),
"exi095":("Organização de bolas paradas ofensivas e defensivas.",
 "Treino de cantos e livres com as posições definidas: marcadores, bloqueios, ataque ao 1.º e 2.º poste e segunda bola.\nDefensivamente, montar a marcação (zona, individual ou mista) e as saídas para o contra-ataque.\nRepetição das variantes preparadas para o jogo.",
 "Cada jogador sabe a sua função\nSegurança: dois jogadores fora da área"),
}
