D={
"exi097":("Variação do centro de jogo com as dinâmicas posicionais da equipa.",
 "Jogo em campo inteiro com a equipa organizada nas suas posições (DC, DD, DE, MD, MC, extremos e PL) contra adversários.\nAs linhas tracejadas marcam os corredores; o objetivo é variar o centro de jogo e explorar o lado contrário à concentração da bola.\nO treinador repõe bolas das laterais para dar continuidade.",
 "Circular por trás para mudar de corredor\nExtremo do lado oposto preparado para receber"),
"exi098":("Dinâmicas de terceiro homem em jogo competitivo.",
 "Espaço retangular com jokers nas linhas e mini-balizas em cada extremidade.\nPara marcar, a equipa tem de fazer pelo menos uma combinação de terceiro homem (A passa a B, que devolve de primeira a C).\nGolo após terceiro homem vale a dobrar.",
 "Apoio curto para soltar de primeira\nTerceiro jogador já em movimento"),
"exi099":("Circuito de passe com as posições da equipa (DC, DL, MC, EXT/PL).",
 "Circuito que reproduz a saída de bola: DC para DL, DL para MC, MC para o extremo/PL e mudança de lado.\nCada jogador segue a bola para a posição seguinte.\nA meio da série, inverter o sentido e introduzir a devolução em apoio.",
 "Receção orientada para o próximo passe\nComunicação antes de receber"),
"exi101":("Posse com dinâmicas de terceiro homem e apoios exteriores.",
 "Duas equipas dentro do retângulo e apoios nas linhas laterais, que jogam com a equipa em posse.\nPonto sempre que a bola chega a um apoio através de uma combinação de terceiro homem.\nAs mini-balizas laterais servem para finalizar após recuperação.",
 "Triângulos constantes à volta da bola\nPasse de primeira para o terceiro homem"),
"exi102":("Finalização específica após passe do treinador, com defesas de referência.",
 "O treinador, junto à lateral da área, passa a bola para um atacante que surge entre os cones.\nO atacante recebe, enquadra e finaliza à baliza com guarda-redes.\nSéries alternadas dos dois lados, com mudança do pé de remate.",
 "Receção orientada para a baliza\nRemate ao primeiro espaço"),
"exi105":("Finalização em filas a partir de passes longos e diagonais.",
 "Quatro filas de jogadores dispostas em diagonal no meio-campo ofensivo.\nCada jogador passa para o avançado, que tabela e devolve; o jogador conduz e finaliza à baliza com guarda-redes.\nRodar de fila a cada remate.",
 "Passe tenso ao avançado\nConduzir de cabeça levantada"),
"exi113":("Jogo lúdico de reação e fuga dentro da área (jogo do mata).",
 "Duas equipas dentro da área. Os jogadores de uma equipa tentam acertar com a bola nos adversários, abaixo da cintura.\nQuem é atingido sai; ganha a equipa que eliminar todos os adversários primeiro.\nVariante com passes obrigatórios antes do lançamento.",
 "Mudanças de direção para fugir\nPasses rápidos para surpreender"),
"exi118":("Jogo setorial 5v5: fixar o adversário e progredir.",
 "Espaço dividido em três setores. A equipa em posse começa no primeiro setor e tem de fixar o adversário para progredir com passe ou condução para o setor seguinte.\nOs defensores só podem sair do seu setor quando a bola entra.\nPonto quando a bola chega controlada ao último setor.",
 "Fixar com a condução antes de soltar\nPasse na linha do colega livre"),
"exi123":("Circuito de passe curto com apoio e desmarcação.",
 "Circuito em linha com cones: passe, devolução em apoio, passe longo e desmarcação para o cone seguinte.\nCada jogador segue a bola.\nA meio da série, alternar o sentido e o pé de passe.",
 "Passe ao pé certo do colega\nRitmo alto e contínuo"),
"exi124":("Posse em meinhos com trabalho de resistência.",
 "Dois meinhos (5 ou 6 contra 2) em quadrados de um lado do campo e quadrados vazios do lado oposto.\nAo sinal, os grupos correm para o quadrado oposto e recomeçam o meinho; quem chega primeiro começa com bola.\nPeríodos curtos com recuperação ativa.",
 "Manter a qualidade do passe com fadiga\nOrganização rápida no novo quadrado"),
"exi125":("Finalização após cruzamento e após passe central.",
 "Filas nos dois corredores com cruzadores junto às linhas e duas filas centrais à entrada da área.\nAlternar: cruzamento de um lado para um jogador da fila central, ou passe central seguido de remate.\nGuarda-redes na baliza; contar golos por equipa.",
 "Atacar o 1.º poste ou o 2.º poste, não ficar parado\nCruzamento para o espaço, não para o jogador"),
}
