D={
"exi049":("Competitividade e finalização em jogos 2x2 em formato de torneio escada.",
 "Vários campos pequenos lado a lado, cada um com duas balizas e jogos de 2x2.\nNo fim de cada jogo curto, a dupla vencedora sobe um campo e a derrotada desce.\nO objetivo é chegar ao campo 1 e lá manter-se.",
 "Rematar sempre que houver espaço\nDefesa agressiva ao portador"),
"exi050":("Jogo formal para aplicar os princípios de jogo da semana.",
 "Jogo 11x11 (ou adaptado ao número de jogadores) em campo inteiro ou reduzido com as linhas laterais recuadas.\nO treinador pode definir condicionantes ligadas ao objetivo do microciclo e pára o jogo para correções pontuais.",
 "Aplicar o que foi treinado durante a semana\nIntensidade e comunicação de jogo"),
"exi051":("Organização da primeira fase de construção contra pressão alta.",
 "A equipa sai a jogar desde o guarda-redes com defesas e médios contra uma equipa que pressiona alto.\nA construção termina quando a bola chega controlada a uma das mini-balizas junto ao meio-campo.\nSe os que pressionam recuperarem, finalizam na baliza grande.",
 "Abrir os centrais e dar linha ao médio\nNão arriscar o passe interior sem apoio"),
"exi052":("Mudança do centro de jogo com quatro balizas para atacar.",
 "Jogo entre duas equipas com duas balizas em cada linha de fundo.\nA equipa em posse pode marcar em qualquer uma das duas balizas que ataca, o que obriga a variar o corredor.\nGolo após mudança de corredor vale 2.",
 "Atrair o bloco para um lado e atacar o outro\nDefesa: basculação rápida"),
"exi053":("Situações de 1x1 com drible e finalização.",
 "Duas filas nos lados do campo. Ao sinal, um jogador de cada fila entra e disputam 1x1 no espaço central até à baliza.\nQuem ataca tem de passar o defensor em drible antes de finalizar.\nAlternar quem começa com a bola.",
 "Mudança de velocidade depois da finta\nDefensor: orientar o atacante para fora"),
"exi055":("Finalização em volume num jogo competitivo a três equipas.",
 "Três equipas: duas jogam dentro do campo e a terceira fica nos apoios exteriores, que jogam com a equipa em posse.\nObjetivo: rematar muitas vezes, com poucos toques antes da finalização.\nA equipa que sofre golo troca com a equipa dos apoios.",
 "Rematar ao primeiro sinal de espaço\nAtacar a recarga"),
"exi056":("Situações de 2x2 com finalização à baliza.",
 "Duas duplas jogam 2x2 à entrada da área, com guarda-redes; a dupla que defende tem mini-balizas para contra-atacar.\nO treinador serve a bola para iniciar cada jogada.\nRotação das duplas a cada golo ou minuto.",
 "Combinações rápidas: tabela e cruzamento\nDefesa: um pressiona, o outro cobre"),
"exi057":("Rabia 4x1 em formato competitivo.",
 "Quadrados com 4 atacantes contra 1 defensor. Cada grupo conta os passes seguidos.\nO defensor troca com o jogador que perde a bola.\nCompetição entre quadrados: vence quem fizer a maior sequência em tempo definido.",
 "Receção orientada\nPasse para o apoio mais afastado do defensor"),
"exi058":("Receção orientada e passe em circuito circular.",
 "Circuito em forma de retângulo com cones em cada vértice e um jogador por cone.\nA bola circula em sentido definido: receção orientada, passe e deslocação para o cone seguinte.\nA meio da série muda-se o sentido e o pé de receção.",
 "Receber com o pé mais afastado\nPasse tenso e rasteiro"),
"exi063":("Finalização a partir de diferentes zonas e combinações numeradas.",
 "Jogadores nas quatro esquinas do espaço, com bolas e guarda-redes nas balizas.\nCada combinação (1, 2, 3 e 4) define o percurso: condução, tabela ou passe longo, terminando com remate.\nRodar as posições para todos passarem por cada zona.",
 "Preparação do remate no último toque\nFinalizar cedo, sem esperar pelo GR"),
"exi067":("Cabeceamento ofensivo e defensivo em jogo lúdico.",
 "Duas equipas em filas junto à baliza. Um jogador de cada equipa entra: um lança a bola ao ar e o adversário tenta cabecear para a baliza enquanto o outro defende.\nPontos para golo de cabeça e para defesa bem conseguida.\nRodar papéis a cada ação.",
 "Atacar a bola, não esperar por ela\nDefesa: ganhar posição e saltar primeiro"),
"exi068":("Meinho em roda com dois defensores no centro.",
 "Os jogadores formam um círculo e circulam a bola a um ou dois toques, com dois defensores no meio.\nQuem erra o passe ou deixa a bola ser intercetada troca com o defensor há mais tempo no centro.\nPontos extra para passes que passam entre os dois defensores.",
 "Passe rápido para o lado contrário à pressão\nCorpo aberto para receber"),
}
