D={
"exi001":("Manter a posse em superioridade com o apoio do joker e atacar o espaço para pontuar.",
 "Campo dividido em dois espaços iguais. Em cada um jogam duas duplas (2x2) com um joker que joga sempre com a equipa em posse, criando 3x2.\nA equipa marca ponto quando entra em condução, ou recebe um passe, dentro da zona de pontuação do lado oposto.\nFormato de torneio: jogos curtos e as duplas rodam de adversário.",
 "Criar linhas de passe com o joker\nAtacar a zona no momento certo (desmarcação de rutura)\nReação imediata à perda"),
"exi002":("Velocidade de reação, orientação no espaço e agilidade num contexto lúdico.",
 "Duas zonas com várias bases marcadas por cones, com os jogadores distribuídos pelas bases.\nAo sinal do treinador, todos deixam a sua base e tentam conquistar uma base livre; o treinador vai retirando bases, e quem fica sem base cumpre uma tarefa ou perde ponto.\nVariante: cada jogador conduz uma bola entre bases.",
 "Reagir ao sinal e não antecipar\nApoios curtos nas mudanças de direção"),
"exi003":("Atacar em superioridade logo a partir da reposição do guarda-redes.",
 "O guarda-redes repõe a bola (pé ou mão) para um dos três atacantes, que atacam a baliza oposta contra dois defensores.\nQuando a jogada termina, entra a vaga seguinte do outro lado, de forma contínua.\nTempo limite para finalizar (cerca de 10 segundos).",
 "Receber orientado para a frente\nFixar o defensor antes de passar\nOcupar largura e profundidade"),
"exi004":("Ocupar a área e finalizar com a estrutura ofensiva em 3-1-2.",
 "Situação de ataque à baliza a partir da entrada da área, com os atacantes organizados em 3-1-2 contra defensores e GR.\nA bola entra por um dos corredores; os atacantes atacam 1.º poste, 2.º poste e entrada da área.\nRotação das posições a cada série.",
 "Chegar à área em timings diferentes\nUm jogador sempre na zona da segunda bola"),
"exi005":("Aceleração em duelo e finalização em velocidade.",
 "Jogadores em filas junto à meia-lua. Ao sinal, dois jogadores saem em sprint para disputar a bola colocada à entrada da área.\nQuem ganha a bola finaliza à baliza; o outro passa a defender.\nRecuperação completa entre repetições.",
 "Primeiro passo explosivo\nProteger a bola com o corpo\nFinalizar depressa, sem conduções a mais"),
"exi006":("Progressão em condução e drible num contexto lúdico e competitivo.",
 "Corredor dividido em várias faixas, com defensores confinados a cada faixa (os guardas do castelo).\nOs atacantes tentam atravessar todas as faixas com a bola controlada e marcar na mini-baliza do fundo.\nSe um defensor rouba a bola, troca de papel com o atacante.",
 "Mudanças de ritmo e de direção\nOlhar para a frente enquanto conduz"),
"exi007":("Ligação entre setores e circulação com a estrutura 3-1-2.",
 "Espaço dividido em três setores por linhas, com mini-balizas nas duas extremidades.\nCada equipa ocupa os setores em 3-1-2 e só pode sair do seu setor com a bola ou para apoiar.\nGolo nas mini-balizas depois de a bola passar pelos três setores.",
 "Médio sempre disponível entre linhas\nAbrir o campo no setor defensivo"),
"exi008":("Atacar a bola de cabeça em cantos, ofensiva e defensivamente.",
 "Cantos marcados alternadamente dos dois lados. Dentro da área, atacantes contra defensores, com guarda-redes.\nOs atacantes procuram o espaço e atacam a bola de cabeça; os defensores disputam a bola aérea e afastam para fora da área.\nContar golos e alívios bem feitos.",
 "Atacar a bola no ponto mais alto\nTiming da corrida, não ficar parado à espera\nDefesa: ganhar posição antes da bola sair"),
"exi009":("Fazer chegar a bola a um jogador livre no meio-campo adversário.",
 "Jogo em campo inteiro com a equipa organizada a partir do guarda-redes.\nO objetivo é ligar com um jogador livre no meio-campo adversário através de circulação e dinâmica de terceiro homem.\nVale ponto sempre que a bola chega controlada a um jogador livre nessa zona.",
 "Atrair a pressão para libertar o colega\nReceber de frente para o jogo"),
"exi010":("Comunicação entre colegas, em ataque e em defesa, num contexto de vagas.",
 "Vagas contínuas de ataque à baliza grande com guarda-redes contra defensores que saem da linha da área.\nQuando os defensores recuperam, saem em transição para as mini-balizas colocadas em diagonal.\nÉ obrigatório falar: quem pressiona, quem cobre, quem pede a bola.",
 "Indicar em voz alta a função de cada um\nCorreções entre colegas durante a jogada"),
"exi011":("Treinar os princípios defensivos: contenção, cobertura e equilíbrio.",
 "Defensores organizados perante atacantes que tentam finalizar na baliza grande.\nO primeiro defensor faz contenção, o segundo cobre e o terceiro garante o equilíbrio do lado oposto.\nSe a defesa recupera a bola, marca ponto nas mini-balizas laterais.",
 "Não se deixar ultrapassar pelo portador\nDistância de cobertura curta\nFechar o espaço interior"),
"exi012":("Jogo por setores com um joker a ligar os dois 2x2.",
 "Campo dividido em dois setores. Em cada setor joga-se 2x2 e um joker ocupa a zona central, jogando com quem tem bola.\nA bola tem de passar pelo joker para chegar ao setor ofensivo.\nGuarda-redes nas duas balizas; os jogadores não saem do seu setor.",
 "Usar o joker como terceiro homem\nMobilidade para criar a linha de passe"),
}
