D={
"exi013":("Drible, finta e 1x1 num contexto lúdico.",
 "Duas filas nos cantos, cada uma virada para uma mini-baliza. Ao sinal, sai um jogador de cada fila; o treinador serve a bola no corredor central.\nQuem ganha a bola ataca a mini-baliza do adversário e o outro defende (1x1).\nVariante: 2x2 com dois jogadores de cada fila.",
 "Enfrentar o defensor com mudanças de ritmo\nProteger a bola ao receber"),
"exi014":("Manutenção da posse em inferioridade defensiva e progressão entre quadrados.",
 "Vários quadrados no campo. Em cada quadrado, 4 jogadores mantêm a posse contra 1 defensor.\nApós um número de passes (ex.: 6), a equipa pode progredir para o quadrado seguinte com passe ou condução.\nCompetição entre grupos: vence quem chegar primeiro ao último quadrado.",
 "Apoios em diagonal ao portador\nPasse tenso, 2 toques no máximo"),
"exi015":("Manter a posse em 3x1 usando o quadrado livre para escapar à pressão.",
 "Três quadrados em linha, cada um com 3 atacantes contra 1 defensor. Um dos quadrados fica livre.\nA equipa em posse pode mudar para o quadrado livre com passe ou condução quando a pressão fecha o espaço.\nQuem perde a bola passa a defender.",
 "Ler quando sair da pressão\nRececão orientada para o espaço livre"),
"exi016":("Jogo de posse com apoios exteriores e mudança de corredor.",
 "Duas equipas jogam no espaço central; nas linhas laterais e de fundo estão apoios de cada cor.\nA equipa em posse tem de usar os apoios para progredir e só pode finalizar depois de a bola passar por um apoio.\nOs apoios jogam a 1 ou 2 toques.",
 "Procurar o apoio mais longe da pressão\nOcupar largura dentro do espaço"),
"exi017":("Reagir à perda e recuperar a bola o mais depressa possível.",
 "Campo dividido em vários corredores com duelos em cada corredor.\nO treinador dá a bola a um dos lados; quem não tem a bola tenta recuperá-la o mais rápido possível.\nCompetição: conta o número de recuperações por jogador em cada série.",
 "Pressão agressiva mas controlada\nFechar a linha de passe antes de atacar a bola"),
"exi018":("Criar linhas de passe (ataque) e tapá-las (defesa).",
 "Espaço dividido em faixas horizontais. A equipa com bola tem de fazer a bola passar de faixa em faixa através de passes.\nOs defensores, um por faixa, tentam tapar a linha de passe com o corpo.\nPonto quando a bola chega à última faixa.",
 "Atacante: desmarcar-se para fora da sombra do defensor\nDefensor: posicionar-se entre a bola e o recetor"),
"exi019":("Construir pelo médio centro contra um bloco de 3 e finalizar em 4x3.",
 "Construção a partir do guarda-redes com a bola a entrar obrigatoriamente no médio centro.\nDepois de o MC receber, a jogada evolui para 4x3 no meio-campo ofensivo até à finalização.\nSe os defensores recuperarem, atacam as balizas no meio-campo com os extremos amarelos a ajudar.",
 "MC a receber de costas protegido ou de frente orientado\nCentrais abertos para dar linha ao MC"),
"exi020":("Construção através dos defesas centrais e do médio centro.",
 "Organização ofensiva a partir do guarda-redes, com os dois centrais e o médio a garantir a saída.\nOs defensores pressionam em inferioridade; a equipa tem de ligar do GR aos DC e ao MC antes de progredir para a finalização.\nSe recuperarem, os defensores finalizam na baliza oposta.",
 "Distância entre centrais e GR\nMédio a aparecer na linha de passe interior"),
"exi021":("Finalização em série a partir de diferentes zonas.",
 "Três estações à entrada da área (esquerda, centro e direita), com jogadores em fila e bolas junto a cada cone.\nCada jogador conduz, faz uma combinação com o colega e finaliza à baliza com guarda-redes.\nRodar de estação a cada série.",
 "Remate colocado antes de potente\nÚltimo toque de preparação para o pé forte"),
"exi022":("Finalizar a cruzamento atrasado (bola para trás, à entrada da área).",
 "Circuito de combinação a partir do meio-campo: passe para o corredor, desmarcação e cruzamento atrasado.\nDois atacantes atacam a área: um fixa o 1.º poste e o outro chega à marca de penálti para finalizar.\nVariante com defensor passivo e depois ativo.",
 "Timing de chegada à zona do atrasado\nCruzamento rasteiro e tenso"),
"exi023":("Duelos 1x1 e 2x2 com disputa de bola aérea.",
 "O treinador lança a bola pelo ar para a zona central entre cones.\nDois jogadores (ou duas duplas) disputam a bola aérea; quem ganha ataca a baliza e o adversário defende.\nAlternar o lado de início e o tipo de lançamento.",
 "Ler a trajetória e posicionar-se cedo\nProteger a bola na queda"),
"exi024":("Coordenação motora com execução técnica em circuito.",
 "Circuito com escada de coordenação, barreiras baixas e estacas de slalom.\nNo fim de cada estação o jogador faz uma ação técnica: passe, receção orientada ou remate.\nGrupos em cada estação, rodar ao sinal.",
 "Qualidade dos apoios antes da velocidade\nOlhar para a bola só no momento da execução"),
}
