D={
"exi025":("Manter a posse em 4x2 aproveitando as arestas livres do quadrado.",
 "Dois quadrados lado a lado. Em cada um, 4 jogadores mantêm a posse contra 2 defensores; duas das arestas não têm apoio (livres).\nA equipa em posse tem de ocupar as arestas com mobilidade para ter sempre linha de passe.\nA cada 8 passes seguidos, ponto; quem perde a bola troca com o defensor.",
 "Mobilidade para ocupar a aresta livre\nPasse para o lado contrário à pressão"),
"exi026":("Rabia em 3x1 com uma aresta livre, exigindo mobilidade constante.",
 "Grupos de 3 contra 1 em quadrados delimitados por cones, com uma aresta sem jogador.\nOs 3 atacantes deslocam-se para garantir duas linhas de passe ao portador.\nQuem perde a bola ou a deixa sair troca com o defensor.",
 "Apoio em ângulo, nunca em linha com o defensor\nMáximo 2 toques"),
"exi027":("Técnica individual em circuito competitivo por equipas.",
 "Circuito com várias estações (condução em slalom, passe contra cone, receção orientada e remate).\nCada equipa percorre o circuito em estafeta; o jogador seguinte só parte quando o anterior termina a estação.\nVence a equipa mais rápida com menos erros (cada erro soma tempo).",
 "Controlo da bola antes da velocidade\nToque com as duas pernas"),
"exi028":("Velocidade de reação e decisão em jogo lúdico (jogo do galo).",
 "Tabuleiro de 3x3 marcado com arcos ou sinalizadores. Duas equipas em fila atrás da linha.\nAo sinal, um jogador de cada equipa corre e coloca o seu colete/cone numa casa do tabuleiro; volta e sai o seguinte.\nVence a equipa que fizer três em linha. Variante com condução de bola.",
 "Decidir antes de chegar ao tabuleiro\nSprint curto e regresso rápido"),
"exi029":("Agilidade e reação em jogo lúdico de fuga e captura.",
 "Os jogadores alinham numa linha lateral e têm de atravessar o campo (o lago) até à linha oposta.\nOs crocodilos, no meio, tentam apanhá-los; quem é apanhado passa a crocodilo.\nVariante com bola: atravessar em condução e os crocodilos roubam a bola.",
 "Mudanças de direção e de ritmo\nUsar os colegas para escapar"),
"exi030":("Finalizar em 2x1 com um defensor a recuperar por trás.",
 "Dois atacantes saem com bola contra um defensor à frente; um segundo defensor parte atrás, em perseguição.\nOs atacantes têm de decidir e finalizar depressa antes da recuperação.\nVagas alternadas dos dois lados do campo.",
 "Atacar o defensor para o fixar\nDecidir cedo: passe ou remate"),
"exi031":("Ataque e defesa em vagas com relação numérica crescente.",
 "Começa em 1x0 até à finalização; logo depois entram novos jogadores e a situação passa a 2x1, 3x2 e 4x3.\nQuem ataca numa vaga defende na seguinte.\nContínuo, com guarda-redes nas duas balizas.",
 "Superioridade: fixar e soltar\nInferioridade: atrasar e fechar o centro"),
"exi032":("Proteção da bola e drible em jogo lúdico individual.",
 "Todos os jogadores com bola dentro de um quadrado. Cada um tenta tirar a bola aos outros para fora do espaço sem perder a sua.\nQuem fica sem bola sai e faz uma tarefa rápida antes de voltar.\nVence quem mais tempo aguentar no quadrado.",
 "Corpo entre o adversário e a bola\nCabeça levantada"),
"exi033":("Ocupação racional do espaço e ligação entre setores.",
 "Campo dividido em três setores por linhas. Cada equipa distribui os jogadores pelos setores (defensivo, médio e ofensivo).\nOs jogadores não saem do seu setor, exceto um que pode acompanhar a jogada.\nGolo só é válido se a bola tiver passado pelos três setores.",
 "Distâncias entre linhas\nApoio frontal ao setor seguinte"),
"exi034":("Comunicação entre colegas em vagas de ataque e defesa.",
 "Duas filas: atacantes com bola e defensores. Saem em pares e disputam a jogada até à baliza com guarda-redes.\nÉ obrigatório comunicar: pedir a bola, indicar pressão, coberturas e trocas de marcação.\nOs defensores que recuperam finalizam nas mini-balizas laterais.",
 "Falar antes de a bola chegar\nNomear o colega"),
"exi035":("Jogo GR+4x4+GR com dois jokers laterais para dar largura.",
 "Jogo 4x4 com guarda-redes, e dois jokers fora das linhas laterais que jogam com a equipa em posse.\nOs jokers jogam a 2 toques e não podem finalizar.\nGolo após cruzamento de um joker vale a dobrar.",
 "Usar os jokers para mudar de corredor\nAtacar a área quando o joker recebe"),
"exi036":("Situações de 4x3 a partir de lançamento longo (LLL).",
 "O guarda-redes ou um defensor faz um lançamento longo para a zona ofensiva.\nQuatro atacantes disputam a primeira e a segunda bola contra três defensores e atacam a baliza.\nSe os defensores recuperam, saem para as mini-balizas.",
 "Ganhar a primeira bola ou a segunda\nApoio curto a quem disputa"),
}
