D={
"exi037":("Técnica de cabeceamento em jogo lúdico.",
 "Jogo em campo reduzido com balizas pequenas, em que a bola circula com as mãos e só vale golo de cabeça.\nO jogador com a bola não pode andar; os colegas movimentam-se para receber.\nVariante: o passe tem de ser feito com um lançamento para o colega cabecear.",
 "Olhos abertos no contacto com a bola\nAtacar a bola com a testa"),
"exi038":("Posse de bola em rabias por quadrados, em formato competitivo.",
 "Quatro quadrados, cada um ocupado por uma equipa. Em cada quadrado, a equipa mantém a posse contra defensores que entram vindos de outra equipa.\nConta-se o número de passes seguidos; ao sinal, as equipas rodam de quadrado.\nVence a equipa com mais pontos no fim das rotações.",
 "Receber já orientado\nComunicar a pressão ao colega"),
"exi039":("Reagir à perda de imediato e impedir a transição adversária.",
 "Dois espaços iguais, cada um com um jogo de posse (4x2 ou 5x3) e mini-balizas nas extremidades.\nAo perder a bola, a equipa tem poucos segundos para a recuperar antes de o adversário marcar nas mini-balizas.\nContagem de recuperações rápidas como ponto extra.",
 "O mais próximo ataca a bola, os outros fecham linhas\nNão recuar sem antes pressionar"),
"exi040":("Duelos de recuperação da bola em velocidade.",
 "Pares de jogadores em cones à entrada da área. O treinador lança ou passa a bola para uma zona; os dois disputam a recuperação.\nQuem recupera finaliza na baliza; o outro tenta impedir.\nRodar pares e alternar o lado do lançamento.",
 "Primeiro passo rápido\nMeter o corpo entre o adversário e a bola"),
"exi041":("Recuperação defensiva após perda, voltando a zonas de equilíbrio.",
 "Jogo em que a equipa atacante, ao perder a bola, tem de recuperar posição atrás da linha marcada antes de defender.\nA equipa que recupera tenta atacar depressa a baliza enquanto a outra se reorganiza.\nOs defensores que não recuam não podem intervir na jogada.",
 "Recuar pelo caminho mais curto para a baliza\nComunicação na reorganização"),
"exi042":("Proteção da bola e cooperação em duplas, em jogo lúdico.",
 "Duplas com bola dentro de um espaço delimitado. Cada dupla tenta roubar a bola às outras e mantê-la dentro do espaço.\nA dupla que perde a bola fica fora durante um tempo curto.\nVence a dupla que resistir mais tempo.",
 "Comunicar com o parceiro\nPasse para o parceiro quando vem a pressão"),
"exi043":("Reação à perda em perseguição (1x0+1).",
 "Um atacante sai com bola em direção à baliza (1x0); um defensor parte atrás, com atraso, para o apanhar (+1).\nO atacante tem de finalizar antes de ser alcançado; se o defensor recupera, ataca a baliza oposta.\nVagas contínuas dos dois lados.",
 "Atacante: conduzir em velocidade para a frente\nDefensor: não desistir, recuperar por dentro"),
"exi044":("Jogo de posse com alvos ('reis') a quem é preciso fazer chegar a bola.",
 "Campo dividido em zonas com um jogador-alvo (rei) em cada extremidade.\nA equipa em posse marca ponto quando consegue passar a bola ao seu rei e recebê-la de volta.\nQuem recebe do rei tem de jogar para a frente.",
 "Criar linha de passe para o rei\nApoio frontal e rutura"),
"exi045":("Posse com um corredor central (fosso) que separa as duas zonas de jogo.",
 "Espaço dividido em duas zonas com um corredor central no meio (o fosso), onde ficam defensores.\nA equipa em posse numa zona tem de fazer a bola atravessar o fosso para os colegas da outra zona, sem que os defensores a intercetem.\nApós a travessia, os defensores trocam de zona.",
 "Esperar pelo momento certo para o passe vertical\nPasse tenso e rasteiro"),
"exi046":("Bola ao capitão com balizas: posse até ao alvo e finalização.",
 "Jogo de posse em que cada equipa tem um capitão dentro de uma zona marcada.\nDepois de ligar com o seu capitão, a equipa pode finalizar nas balizas.\nOs capitães rodam a cada golo.",
 "Mobilidade para libertar o capitão\nFinalizar logo depois da ligação"),
"exi047":("Ataque em superioridade 3x2 em vagas contínuas.",
 "Três atacantes saem com bola contra dois defensores e atacam a baliza com guarda-redes.\nQuando a jogada termina, os defensores e um jogador novo atacam no sentido contrário.\nTempo máximo para finalizar em cada vaga.",
 "Portador fixa o defensor\nApoios em largura e profundidade"),
"exi048":("Velocidade de execução com finalização.",
 "Os jogadores saem das filas junto à meia-lua em percursos marcados por cones até à entrada da área.\nNo fim do percurso recebem a bola do treinador e finalizam à baliza com guarda-redes.\nCompetição entre filas pelo número de golos.",
 "Manter a velocidade até à finalização\nRemate com o pé mais afastado do GR"),
}
